data:
  raw_dir: "data/raw"
  proc_dir: "data/processed" 
  resources_dir: "resources"

cohort:
  min_los_icu_days: 1.0
  min_duration_hours: 24
  max_duration_hours: 240
  min_age: 15

processing:
  input_window_h: 6
  gap_h: 6
  pred_window_h: 4