defaults:
  - _self_

hydra:
  run:
    dir: artifacts/tests/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

tests:
  run_unit: true
  run_integration: true
  run_e2e: true

paths:
  test_root: "src/test"
  src_root: "src/hint"
  resources_root: "resources"
  report_template: "test_coverage_template.html"

logging:
  level: "INFO"
  file_name: "tests.log"

seeding:
  seed: 42

coverage:
  targets:
    - "src/hint"
  omit: []
  branch: true
  config: "pyproject.toml"
  reports:
    term: true
    xml: "coverage.xml"
    html: "coverage_html"
    json: "coverage.json"
